### ISSUE TITLE
[bug] nemegyezés a szöveg és az ábra között

### ISSUE THREAD

**Issue by Omcsesz** [FTSRG/remo-jegyzet#5]
```
   97. sor: 
```

Induljunk ki a Fővám térről: átszállás nélkül az Astoria és a Rákóczi tér megállókat érhetjük el, ...
Helyesen: Induljunk ki a Fővám térről: átszállás nélkül a Kálvin tér és a Rákóczi tér megállókat érhetjük el, ...

**Comment by szarnyasg** [comment]
Köszi. Nem túl gyorsan, de végül ki lett javítva!
