### ISSUE TITLE
Értelmetlen mondat

### ISSUE THREAD

**Issue by vankodg** [FTSRG/remo-jegyzet#9]
3.2.2. Gráfmodelleknél, a 3.13. ábra feletti megjegyzésben a következő mondat nyelvtanilag értelmetlen:

Az _instance of_ viszony helyett gyakran annak inverzét, a _type of_ (x _típusa_ y-nak) viszonyt.

**Comment by szarnyasg** [comment]
Köszönjük, javítottam!
